In [ ]:
# Task 1
import numpy as np
class MinHeap:
  def __init__(self,capacity):
    self.__capacity=capacity
    self.__heap=np.array([None]*(capacity+1))
    self.__heap_size=1

  def insert(self,inserted_value):
    if self.__heap_size>=len(self.__heap):
      return "No Space Left To Insert"
    self.__heap[self.__heap_size]=inserted_value
    self.__swim(self.__heap_size)
    self.__heap_size+=1

  def __swim(self,children_index):
    if children_index==1:
      return
    parent_index=children_index//2
    if self.__heap[children_index]<self.__heap[parent_index]:
      temp=self.__heap[parent_index]
      self.__heap[parent_index]=self.__heap[children_index]
      self.__heap[children_index]=temp
      self.__swim(parent_index)
    return

  def extractMin(self):
    if self.__heap_size==1:
      return "Nothing to remove in the heap"
    temp=self.__heap[1]
    self.__heap[1]=self.__heap[self.__heap_size-1]
    self.__heap[self.__heap_size-1]=temp
    self.__heap_size-=1
    self.__sink(1)
    return temp

  def __sink(self,parent_index):
    left_child_index=2*parent_index
    right_child_index=2*parent_index+1
    smallest = parent_index

    if left_child_index < self.__heap_size and self.__heap[left_child_index] < self.__heap[smallest]:
      smallest = left_child_index
    if right_child_index < self.__heap_size and self.__heap[right_child_index] < self.__heap[smallest]:
      smallest = right_child_index

    if smallest != parent_index:
      temp = self.__heap[parent_index]
      self.__heap[parent_index] = self.__heap[smallest]
      self.__heap[smallest] = temp
      self.__sink(smallest)
    return

  def sort(self):
    sorted_array=np.zeros((self.__heap_size-1),dtype=int)
    for i in range(len(sorted_array)):
      sorted_array[i]=self.extractMin()
    return sorted_array

  def getHeap(self):
    result = np.zeros(self.__heap_size - 1, dtype=int)
    index = 1
    while index < self.__heap_size:
      result[index - 1] = self.__heap[index]
      index += 1
    return result

heap=MinHeap(5)
heap.insert(15)
heap.insert(5)
heap.insert(20)
heap.insert(25)
heap.insert(30)
heap.sort()

array([ 5, 15, 20, 25, 30])

In [ ]:
# Task: 2
class MaxHeap:
  def __init__(self,capacity):
    self.__capacity=capacity
    self.__heap=np.array([None]*(self.__capacity+1))
    self.__heap_size=1

  def insert(self,inserted_value):
    if self.__heap_size>len(self.__heap):
      return "No Space Left To Insert"
    self.__heap[self.__heap_size]=inserted_value
    self.__swim(self.__heap_size)
    self.__heap_size+=1
    return

  def __swim(self,children_index):
    if children_index==1:
      return
    parent_index=children_index//2
    if self.__heap[children_index]>self.__heap[parent_index]:
      temp=self.__heap[children_index]
      self.__heap[children_index]=self.__heap[parent_index]
      self.__heap[parent_index]=temp
      self.__swim(parent_index)
    return

  def extractMax(self):
    if self.__heap_size==1:
      return "Nothing to be removed in the heap"
    temp=self.__heap[1]
    self.__heap[1]=self.__heap[self.__heap_size-1]
    self.__heap[self.__heap_size-1]=temp
    self.__heap_size-=1
    self.__sink(1)
    return temp

  def __sink(self,parent_index):
    left_child_index=2*parent_index
    right_child_index=2*parent_index+1
    greatest=parent_index
    if left_child_index<self.__heap_size and self.__heap[left_child_index]>self.__heap[greatest]:
      greatest=left_child_index
    if right_child_index<self.__heap_size and self.__heap[right_child_index]>self.__heap[greatest]:
      greatest=right_child_index
    if greatest!=parent_index:
      temp=self.__heap[parent_index]
      self.__heap[parent_index]=self.__heap[greatest]
      self.__heap[greatest]=temp
      self.__sink(greatest)
    return

  def sort(self):
    sorted_array=np.zeros((self.__heap_size-1),dtype=int)
    for i in range(len(sorted_array)):
      sorted_array[i]=self.extractMax()
    return sorted_array

  def getHeap(self):
    result = np.zeros(self.__heap_size - 1, dtype=int)
    index = 1
    while index < self.__heap_size:
      result[index - 1] = self.__heap[index]
      index += 1
    return result

heap=MaxHeap(5)
heap.insert(15)
heap.insert(5)
heap.insert(20)
heap.insert(25)
heap.insert(30)
heap.sort()

array([30, 25, 20, 15,  5])

In [ ]:
# Task:3

def minimizing_load(tasks,m):

  my_heap=MinHeap(m)
  final_array=np.zeros(m,dtype=int)

  for j in range(m):
    my_heap.insert(0)

  for i in tasks:
    smallest_value=my_heap.extractMin()
    inserted_value=i+smallest_value
    my_heap.insert(inserted_value)

  for k in range(m):
    final_array[k]=my_heap.extractMin()
  return final_array


tasks=np.array([2,4,7,1,6],dtype=int)
print(minimizing_load(tasks,4))

[2 4 7 7]


In [ ]:
# Task:4

def find_top_largest_elements(nums,k):
  my_heap=MaxHeap(len(nums))
  for i in nums:
    my_heap.insert(i)
  final_array=np.zeros(k,dtype=int)
  for j in range(len(final_array)):
    final_array[j]=my_heap.extractMax()
  return final_array
nums=np.array([4,10,2,8,6,7],dtype=int)
find_top_largest_elements(nums,3)

array([10,  8,  7])